Add extra meter sensors (EG, Eastron meter)
hultenvp/solis-sensor pull request #333
Opened 2023-10-23 09:28 UTC by special-K-Ken

Add a couple of extra sensors to measure grid under current and voltage - ie the Eastron or similar meter (not EPM).

This is from the Solis spec and I've verified the data is returned in another app (c#).

2023-10-27 12:01 UTC, hultenvp requested changes
Please test with HA. I cannot modify and test myself

2023-10-27 12:01 UTC, hultenvp commented on custom_components/solis/soliscloud_api.py
> +        METER_ITEM_A_CURRENT:             ['meterItemACurrent', float, 3],
How can this work? According to the 2.0 spec the fields are called 'iA' and 'uA' respectively. Did you test your changes with HomeAssistant?

2023-10-28 16:08 UTC, special-K-Ken commented on custom_components/solis/soliscloud_api.py
> +        METER_ITEM_A_CURRENT:             ['meterItemACurrent', float, 3],
You're right, I have iA and uA in my code but pasted the wrong fields in here. Thanks

2023-10-28 16:10 UTC, special-K-Ken commented
Extra fields added, and corrected the fields from inverterDetail API

2023-10-28 16:45 UTC, special-K-Ken commented
![image](https://github.com/hultenvp/solis-sensor/assets/25320504/6455121b-9584-4c2e-9ec8-38597b1ed34d)

No errors reported in mass terminal

2024-01-05 13:50 UTC, hultenvp approved these changes

2024-01-05 14:08 UTC, merged